### ISSUE TITLE
project appears to be more about grandstanding than encouragment

### ISSUE THREAD

**Issue by ninjaaron** [jkup/rejected.us#137]
Many of the submissions seem to be about telling non-employers how much they missed out or general self-affirmation.

Furthermore, everyone knows that it's hard to get a job at the top companies in Silicon Valley. They turn away hundreds of applicants for each one they hire. I guess I'm not sure who this project benefits.

**Comment by jkup** [comment]
I've gone back and forth on closing this project for a while. I started it because I really do believe that rejection is a part of life and I thought sharing stories would help people through potentially difficult times. I've heard lots of criticism about the project but I also get lots of emails and messages from people saying it helped them through a tough time so I leave it open!

If you have any ideas for adjusting the tone or message to be more positive, I'm all ears!
