### ISSUE TITLE
Rejected by School, Now at a Billion Dollar Company

### ISSUE THREAD

**Issue by daVinciCEB** [jkup/rejected.us#46]
I was at the University of Illinois at Urbana-Champaign for a year. The school academics office was telling me that I  had to take three semesters of Physics, including Quantum Physics and Thermodynamics, and that if I didn't like that, then I didn't belong at the school. I dropped out, and was almost immediately hired as a freelance contractor at a billion dollar investment company, and told that I could name my own price. Suck it, UIUC.

**Comment by jkup** [comment]
Thank you! Added.

**Comment by kfogel** [comment]
This isn't a story of you being rejected, @daVinciCEB :-).  The only rejection here is that you rejected UIUC (not the other way around), and then you landed a great job (congratulations!) with no rejection involved at all -- quite the opposite.

My guesses about @jkup's goals for this site might be wrong, so I'll just mention this here and let @jkup decide whether he wants a PR against [stories.js](/Rejectedus/rejected.us/blob/master/src/data/stories.js).

**Comment by daVinciCEB** [comment]
@kfogel firstly, this was closed and accepted by @jkup 3 years ago... and is already in [stories.js](https://github.com/Rejectedus/rejected.us/blob/master/src/data/stories.js#L621).

Secondly, I'm not sure why you're going through old issues and trying to pick them apart, but it seems like this is a personal problem for just you, as Jon was ok with adding this already back when he closed it three years ago.

And finally, I'd say that being told you don't belong somewhere is rejection. If you read through what I wrote, you would have seen that UIUC specifically told me that if I didn't like their way, then I didn't belong there. To me, and apparently to most people, this is a rejection.

**Comment by kfogel** [comment]
Hi, @daVinciCEB.  I don't know why I decided to comment either, so that makes two of us :-).  I did read what you wrote -- that's how I got here: by encountering the story on the front page and being surprised by it, after which I went and found this issue to comment.  What happened between you and UIUC doesn't sound quite like rejection to me, but that's a judgement call and a question of definition; reasonable people can certainly disagree.  Ultimately it's @jkup's call, which was why I addressed my question to him.
